apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}-lb
  labels:
    name: {{ include "helm.name" . }}-lb
spec:
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    app: {{ include "helm.name" . }}
  type: LoadBalancer